### ISSUE TITLE
提问: 会一直维护吗?

### ISSUE THREAD

**Issue by zhwandzcx** [xqymain/RenewMicrosoftE5#1]
rt

**Comment by zhwandzcx** [comment]
我看了你的DEMO站, 很酷,我也学习准备搞一个

**Comment by xqymain** [comment]
首先感谢您对本项目的关注:)
由于这只是个续期的项目，一直没有太过关注，就没看到这个issue，先表示抱歉。
Demo站我自己也一直在用，主要问题是在国内下载速度过慢，经分析是Mainland-HK的线路瓶颈，但是通过一些手段还是可以取得不错的速度的。
而且这种储存方式成本几乎为0，安全系数也高（特别是加密盘+Onedrive的差异同步），所以我会一直维护下去的。
